version: '3.8'
services:
  frontend:
    image: getsnowboard/snowboard_ui:latest
    volumes:
      - nginx_certs:/certs
    links:
      - "app:app"
    ports:
      - 80:8080
      - 443:8443
  app:
    image: getsnowboard/snowboard_api:latest
    links:
      - "arangodb:arangodb"
      - "search:search"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - nginx_certs:/certs
  search:
    image: getmeili/meilisearch:v0.19.0
    environment:
      - MEILI_MASTER_KEY=50dcbf2980cbdf11e15fbc3bbd5d64aaf3bff1932993d1da66bf96574821a9aa
      - MEILI_ENV=production
      - MEILI_NO_SENTRY
    volumes:
      - meili_data_container:/data.ms
  arangodb:
    image: arangodb/arangodb:3.7.6
    command: --http.keep-alive-timeout=3600
    environment:
      - ARANGO_ROOT_PASSWORD=snowadmin
    hostname: 'arangodb'
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps


volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
  meili_data_container:
  nginx_certs: