version: '3.8'
services:
  frontend:
    image: getsnowboard/snowboard_ui:latest
    volumes:
      - nginx_certs:/certs
    links:
      - "app:app"
    ports:
      - 80:8080
      - 443:8443
  app:
    image: getsnowboard/snowboard_api:latest
    links:
      - "arangodb:arangodb"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - nginx_certs:/certs
  arangodb:
    image: getsnowboard/snowboard_db:latest
    command: --http.keep-alive-timeout=3600
    environment:
      - ARANGO_ROOT_PASSWORD=snowadmin
    hostname: 'arangodb'
    volumes:
      - arangodb_data_container:/var/lib/arangodb3

volumes:
  arangodb_data_container:
  nginx_certs:
